version: '3.8'

services:
  postgres:
    image: postgres:16

    container_name: expense-postgres

    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - expense-tracker-net

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine

    container_name: expense-redis

    ports:
       - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - expense-tracker-net

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - expense-tracker-net


volumes:
  postgres_data:
  redis_data:

networks:
  expense-tracker-net:
    driver: bridge