spring.application.name=ai-service
server.port=8082

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.model=${GEMINI_API_MODEL:gemini-3.5-flash}

report.service.url=${REPORT_SERVICE_URL:http://localhost:8080}